### ISSUE TITLE
API documentation

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#1]
## introduction
Figure out some way to document each endpoint so developers and 3rd party consumers of our API can understand how to use it.
Once this is determined all endpoints can follow the processes to be automatically documented. 

## constraints/parameters
- automatically generated if possible
- be easy to view and understand by both humans and non-human entitities (for example generated in HTML or JSON) 
- show field names and datatypes of payloads for requests and responses 
- potentially allow for easy testing

## decision 
- openAPI: [js-doc](https://www.npmjs.com/package/swagger-jsdoc) and [swagger-ui-express](https://www.npmjs.com/package/swagger-ui-express)

## tasks 
- [x] install libraries 
- [x] create higher level apidoc file
- [x] annotate existing first endpoint 
- [x] generate apidoc  
- [x] test documentation
- [x] add new workflow steps into internal documentation
- [x] annotate remaining endpoints
