### ISSUE TITLE
EPIC: initial workflow and tooling for manual endpoint testing, validation, and documentation

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#10]
## introduction
 Postman was being used but now they do not allow storing data locally and need synch with cloud. All of my Postman environments were deleted!

we need some sort of tooling/workflow to test and document endpoints. IE,that payloads are being validated, endpoints are responding with the right body/statuses. once this is determined, create wiki page to describe organization and workflow. 

- exploring using cURL within shell scripts or TS native in order to make the manual tests part of the codebase
- explore following industry standard openAPI3

## constraints/parameters
- if possible, maintain single source of truth for expectations for endpoints
- must be able to retest same endpoints with same config/payloads repeatedly
- tools must be free to use, resistant to changes in technology
- must be able to test payloads, response bodies, but also cookies since JWTs are stored in http only cookies
- be able to use source of truth for validation in as well
- if possible, should be able to be easily expanded to automated endpoint testing if needed

## tasks 
- [x] determine tooling and workflow for manually testing endpoints (cURL, shell script)
- [x] determine tooling and workflow for endpoint validation and documentation (openAPI: swagger-jsdoc, swagger-ui-express, express-openapi-validator)
- [x] create stub of manual tests (one working example in codebase)
- [x] #1 
- [x] #5 
- [x]  create documentation for entire workflow when adding a new endpoint
- [x] add manual tests, documentation, validation, for existing endpoints
