### ISSUE TITLE
custom errors and error handling flow for service and api level errors

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#14]
## introduction
exception handling with javascript is handled using Errors. to add uniformity to how API errors are handled, a new category of error with subtypes for common API errors. this will allow for more useful information when logging and more consistent response generation by the API. express-openapi-validator. 
to be more informative, lower level errors can be thrown that bubble up to the highest API level errors. 

## constraints 
- nested errors with service level errors bubbling up to API level errors
- contains path
- contains status code 
- contains error message
- contains date
- errors thrown conform to openAPI spec for endpoints 

## tasks 
- [x] create service-level UserDataService errors with an extendable context field
- [x] create service-level SqlUserDataService errors that include query in question
- [x] create generic `APIError` type that incorporates a extendable context field
- [x] create error for 404 not found  derived from `APIError`
- [x] update the error handling middleware to handle new types of errors and stub out the logging there(console.log for now)
- [x] add this error to endpoints/SqlUserDataService operations 
- [ ] (OPTIONAL) create error for 403 forbidden  derived from `APIError` (this will probably need to be handled when creating authorization middlware)
