### ISSUE TITLE
convert User library to service

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#15]
## introduction
the User resource has persisted values and may involve authentication mechanisms. Originally, the User resource was 'hardcoded' to use a mysql DB  but it is possible and desirable to be able to use different technologies or external services to represent Users (ex: AWS amplify for stronger authentication, in memory storage for testing ).

By writing an abstract interface, then writing each variant of the User service to implement that interface, we can ensure that swapping the technology used can be done without breaking the code that consumes the service. 

Down the line, this service-oriented architecture could more easily be turned into a micro-service architecture if needed.

## constraints/parameters 
- interface should contain all necessary operations on Users needed by rest of app 
  - create, read, update, delete 
- service methods should take matching arguments and return types to the existing implementation of User 
-  service methods should throw errors and return meaningful values to code that consumes them
- service methods should be asynchronous to interact with external technologies 

## tasks
- [x] write User service interface 
- [x] implement SQL User service class with function stubs
- [x]  implement and test retrieve operation method 
- [x] modify controller code to use service
