### ISSUE TITLE
db teardown script. add admin scripts as npm commands

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#19]
## introduction
though the goal is to make all persisted data accessible through services w swappable technologies, the core app currently relies on SQL services for all persisted data. 

There is currently a startup admin script that can be run to create tables and populate them with a set of test data, but it would be useful to have one to teardown the sql DB to starting state and one to reset any data to the freshly populated state. 

These can be run as npm commands. 

## constraints 
- must be able to execute the all scripts as an NPM commands 
- each NPM command should be able to be executed independently without any errors / dependencies on other NPM commands
- any CRUD action on resources should use the app's CRUD service operations so data that is in DB is usable by app

## tasks
- [x] update populateDB script to use new service-based CRUD operations (IE `UserDataService.create(data)`
- [x] create new `teardownDB` script to drop all tables 
- [x] test `tearDownDB` script to see if it drops all tables from db client 
- [x] test `populateDB` script to see if it populates tables from db client
- [x] try out a couple RESTful endpoint requests to see if app can successfully use data
- [ ] create new `resetDB`  script while db is already populated and modified to see if it returns to `populateDB` state
- [x] modify package.json to add new commands
  - [x] `npm run populateDB`
  - [ ] `npm run tearDownDB`
  - [ ] `npm run resetDB`

**Comment by space-apes** [comment]
note the new commands are `npm run populateDB` and `npm run clearDB`. no reset command
