### ISSUE TITLE
add transaction service

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#20]
## introduction
the Transaction resource has persisted values and may involve authentication mechanisms. Originally, the User resource was 'hardcoded' to use a mysql DB  but it is possible and desirable to be able to use different technologies or external services to represent Users (ex: AWS amplify for stronger authentication, in memory storage for testing ).

By writing an abstract interface, then writing each variant of the Transaction service to implement that interface, we can ensure that swapping the technology used can be done without breaking the code that consumes the service. 

Down the line, this service-oriented architecture could more easily be turned into a micro-service architecture if needed.

## constraints/parameters 
- interface should contain all necessary operations on Transactions needed by rest of app 
- service methods should take matching arguments and return types to the existing implementation of Transaction
-  service methods should throw errors and return meaningful values to code that consumes them
- service methods should be asynchronous to interact with external technologies 

## tasks
- [x] write `TransactionDataService` interface 
- [x] implement SQL Transaction service class that extends `TransactionDataService` with function stubs
- [x] create Errors for both service and api levels
- [x]  implement and test retrieve operation method 
- [x] modify controller code to use service 
- [x] test at api level
