### ISSUE TITLE
add unit tests, unit test procedure documentation for service-level operations

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#23]
## Introduction
Allow for test-driven development and test smallest logical units of code before attempting to integrate them into rest of app. 
## Constraints
- use popular vetted open source tooling
- ease and  clarity when adding tests for new features
- allows for one set of tests to be used on all different implementations of services with minimal adjustment
- any tests on persisted stores should allow for mockup data stores to avoid affecting working data
## Tasks 
- [ ] identify tooling that best fits needs
- [ ] add test for one service operation to experiment
- [ ] add documentation for workflow for adding unit test 
- [ ] write tests for any existing service level operations
