### ISSUE TITLE
EPIC: Testing Workflow at Multiple Layers

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#24]
## introduction 
TESTING GOOD. add testing procedure, tooling and implementations at service operation level, API endpoint level, and integration level.  (or perhaps combine last 2). 

## constraints 
- ease/clarity of adding new tests as features are added 
- allow for swapping in or out different implementations of services 
- any testing on persisted data should allow for interacting with mock data stores to avoid affecting working data stores
## tasks 
- [ ] decide on testing approach and tooling for service level
- [ ] decide on testing approach and tooling for api level
- [ ] decide on testing approach and tooling for integration level
- [ ] write write any high level documentation needed
