### ISSUE TITLE
add API-level and integration tests, integration test procedure, documentation

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#25]
## Introduction
A full suite of tests to discover issues at highest level by making use of all critical API endpoints and services in coordination when adding a new API feature. 
## Constraints
- use popular vetted open source tooling
- ease and  clarity when adding tests for new features
- allows for one set of tests to be used on all different implementations of services with minimal adjustment
- reach full coverage for API endpoints
- ability to temporarily store and test contents of cookies for JWT
- ability to select different databases for anything testing any endpoints relying on SQL databases for testing without affecting working data stores
## Tasks 
- [x] experiment using at least a combination of api resources
- [x] add documentation for workflow 
- [x] build up set of integration tests for current api resources
