### ISSUE TITLE
initiator endpoints for BE session resource

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#31]
## Introduction
we have already done some experimentation with JWTs and authentication. Now make an actual set of session endpoints to perform authentication. Authorization for specific resources can be handled further down the line. 

## Constraints
- endpoints: 
  - `POST api/session/createRegisteredSession`: create/set new session token for initiator registered user
    - request: 
      - `email`: credentials when creating new user
      -  `password`: credentials when creating new user
      - `displayedName`: name when selecting items on receipt
      - `roomName`: value for socket connection broadcast
    - response: 200 and sets jwt with, at minimum body fields 
      - `userId`
      - `roomName` 
      - `displayedName` 
  - `POST api/session/createGuestSession`: create/set new session token for initiator guest user
   - request: 
      - `displayedName`: name when selecting items on receipt
      - `roomName`: value for socket connection broadcast
    - response: 200 and sets jwt with, at minimum body fields 
      - `userId`
      - `roomName` 
      - `displayedName` 
- stateless for server
- expires after 20 mins 
- 'serviceable'.. can swap technologies and adhere to an interface. (i am thinking aws cognito down the line) 
- add service level tests for local session service 
- add API level tests to apply to any session implementation

## Tasks 
- [x] research cognito JWT body shape and make decisions about fields needed for app (`roomName`, `userId`, `expires`) 
- [x] create interface stub for session service
- [x] implement local session service 
- [x] create unit tests for session service methods  
- [x] write openAPI stubs for `api/sessions` endpoints
- [x] add API level tests for the endpoints
