### ISSUE TITLE
initiator session start form on landing page

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#36]
## Introduction
landing page will give initiator user the ability to kick off a new transaction by setting the `roomName` that will be shared by all participants. 

2 options: sign in as guest or login. this should do 3 things: 
- retrieve new JWT 
- update local state using values from JWT 
- transition to receipt scanning page 

## Constraints 
- guest form should require 
  - `displayedName`
  - `roomName`
- registered form should require 
  - `displayedName`
  - `roomName`
  - `email`
  - `password`
- form should not proceed unless values set 
- page should not proceed unless receives 200
- context needs to be updated to hold new values    

## Tasks
- [x] add form options with 2 ways of submitting for guest and registered
- [x] ensure client side validation for form values
- [x] handle cases where BE does not respond 200
- [x] update context definition and have form submission update value
- [x] create rough `receipt scanning` page 
- [x] cause successful form selection to transition to that page
