### ISSUE TITLE
create BE transactionSessionService and create first REDIS implementation

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#39]
## Introduction 
We have already added session cookies to confirm identity of users and forward them to correct page on react app. If a user is disconnected then reconnected, they need to be able to retrieve the short term transaction data that is shared across the group. This data is currently stored as an array running on BE application process, but it would be nice to have something that is external, quick, scalable.

- the room name 
- the initiator user 
- the business name 
- the current receiptItems 
  - price 
  - name
  - user that has claimed payment

When the transaction is complete, that data can be moved to longer term `transactionDataService`

## Tasks
- [ ] get REDIS server and driver working
- [ ] add .env entries for REDIS
- [ ] determine interface for service / data model on REDIS 
- [ ] create  REDIS service 
- [ ] test redisTransactionSesssionService methods 
- [ ]
