### ISSUE TITLE
API validation

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#5]
## introduction 
check fields, types, and values of content sent through request bodies and ensure that any invalid requests are rejected and informative responses are given

## constraints/parameters 
- contract-first and derived from openAPI spec
- easily extensible 
- API level errors can be triggered by service level errors that bubble up
- easy to integrate into workflow for new endpoints
- preferably set up at middle-ware level

## tasks
- [x] determine what library to use (explore express-openAPI-validator) or write own
- [x] test with a single endpoint
- [x] add to any internal documentation if extra steps are needed when creating new endpoint
