### ISSUE TITLE
EPIC: Incoming User / early flow

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#6]
## Introduction
The login flow determines the experience the user has when they navigate to either the base URL or follow a referral link to join a transaction in progress. This includes which page they land on, the state of the global context for them, authorization for accessing certain resources (IE the ability to view previous transactions that they were a part of, but not other transactions) among other things. It will need to be broken into smaller individual issues.  

## general constraints/parameters
- a transaction is defined as an instance of a receipt with a specific business name and date, set of items on the receipt, and users associated
- each transaction has one 'initiator' user and any number of other users that agree to split the costs of the receipt in various ways
- initiator users access base URL to create new transaction, then generate unique and secure referral URLs for non-initiator users to join that transaction
- all users successfully associated with a transaction have a stored JWT that has a key `roomName`
- There are both registered users (who can see their transaction history) and guest users,  and therefore there must be login flows for both
- Users  may either be with or without JWTs. Users just accessing base URL or referral link do not have JWTs yet. There may be users that attempt to skip ahead in the flow without having JWTs also for malicious or non-malicious reasons. Hopefully some middleware can be added to check which page/resource user is attempting to access and JWT and redirect to home screen if user is not authorized. 
- there are transactions that either have not occurred yet (invalid room numbers), are currently occurring, have been resolved and persisted, or have expired without final commitment 
- every transaction should be isolated such that users that are not associated with the transaction should not be able to gain information or affect that transaction in any way

--- 

## issues: 
- [x]  #7 
- [x] #31 
- [ ] #30 
- [ ] #8 
- [ ] ['start transaction' flow for both guest and registered user that gives JWT with `roomName` and also referral link #9](https://github.com/space-apes/receiptAppTS/issues/9)
- [ ] create endpoint to handle referral links to navigate user to receipt select page and give JWT with correct `roomName`
- [ ] create middleware that checks `roomName` and navigates user to receipt select page or back to home page if unauthorized
