### ISSUE TITLE
login user flow

### ISSUE THREAD

**Issue by space-apes** [space-apes/receiptAppTS#8]
## introduction 
create endpoint and FE flow that allows users that have already registered to login. this should update the JWT if there is one already and the global context for `userId` then redirect to whatever page they were on before they logged in. 

## parameters/constraints
- validation on fields
  - string email
  - string password 
- authentication using Argon2 library
- HTTP status codes and useful but secure error messages

## tasks 
- [ ] endoint to POST, should also update JWT and global context for `userId`
- [ ] react page with form to submit values, POST to endpoint, navigate user back to page they were on. 
- [ ] links to login on appropriate pages (base URL, referral link, receipt select)
